// by  johnnydurao1802@gmail.com
import nichaImg from "./../../../assets/projects/nicha/nicha-rosa.png";
import nichaVideo from "./../../../assets/projects/nicha/nicha-sabores.mp4";

import marketplaceImg from "./../../../assets/projects/oponto/ponto-branco.png";
import marketplaceVideo from "./../../../assets/projects/oponto/oPontoSupermarket.mp4";

export const PROJECTS_DATA = [
  {
    id: 1,
    title: "Gestão de Encomendas – Sabores da Titi Nicha",
    status: "Em Desenvolvimento",
    technologies: "Bootstrap, PHP, MySQL, Blade",
    description:
      "Sistema web para gestão de encomendas de doces e produtos alimentícios, com cadastro de clientes, produtos e relatórios de vendas.",
    image: nichaImg,
    video: nichaVideo,
    timeline: {
      steps: [
        { key: "planejamento", title: "Planejamento", description: "Definição de requisitos e cronograma", completed: true },
        { key: "desenvolvimento", title: "Desenvolvimento", description: "Implementação das funcionalidades principais", completed: true },
        { key: "testes", title: "Testes", description: "Validação de funcionalidades e correções", completed: false },
        { key: "deploy", title: "Deploy", description: "Publicação do sistema em produção", completed: false },
      ],
      currentStep: "desenvolvimento",
    },
  },
  {
    id: 2,
    title: "Marketplace Moderno",
    status: "Em Desenvolvimento",
    technologies: "React, Laravel, MySQL, Tailwind",
    description:
      "Plataforma de marketplace moderna, responsiva, com filtros AJAX, scroll infinito, carrinho de compras e visualização detalhada de produtos.",
    image: marketplaceImg,
    video: marketplaceVideo,
    timeline: {
      steps: [
        { key: "planejamento", title: "Planejamento", description: "Estrutura de banco e wireframes", completed: true },
        { key: "desenvolvimento", title: "Desenvolvimento", description: "Front-end React e Back-end Laravel", completed: true },
        { key: "testes", title: "Testes", description: "Testes de performance e responsividade", completed: false },
        { key: "deploy", title: "Deploy", description: "Lançamento do marketplace", completed: false },
      ],
      currentStep: "deploy",
    },
  },
  {
    id: 3,
    title: "Aplicativo Mobile Fitness",
    status: "Em Desenvolvimento",
    technologies: "Flutter, Firebase",
    description: "App para acompanhamento de treinos e metas de saúde.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 4,
    title: "Sistema de Reservas para Hotéis",
    status: "Em Desenvolvimento",
    technologies: "React, Node.js, MongoDB",
    description: "Sistema web para reservas de quartos, gestão de clientes e pagamentos online.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 5,
    title: "Plataforma Educacional Online",
    status: "Em Desenvolvimento",
    technologies: "Django, Python, PostgreSQL",
    description: "Portal para cursos online, quizzes e certificados automáticos.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 6,
    title: "Sistema de Gestão de Inventário",
    status: "Em Desenvolvimento",
    technologies: "Laravel, PHP, MySQL",
    description: "Controle de estoque, pedidos e relatórios para pequenas empresas.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 7,
    title: "Blog Pessoal Interativo",
    status: "Em Desenvolvimento",
    technologies: "Next.js, Tailwind CSS",
    description: "Blog com comentários em tempo real, likes e compartilhamento social.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 8,
    title: "Sistema de Pagamentos e fatura Online",
    status: "Em Desenvolvimento",
    technologies: "Node.js, Express, Stripe API",
    description: "Plataforma de pagamentos segura para e-commerce e serviços digitais.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 9,
    title: "Dashboard Analytics",
    status: "Em Desenvolvimento",
    technologies: "React, D3.js",
    description: "Painel interativo para análise de dados e métricas empresariais.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 10,
    title: "Aplicativo de Delivery",
    status: "Em Desenvolvimento",
    technologies: "React Nactive, Firebase",
    description: "App para pedidos de comida com geolocalização e rastreio em tempo real.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
  {
    id: 11,
    title: "Aplicativo de Portfólio",
    status: "Em Desenvolvimento",
    technologies: "React Nactive, Firebase",
    description: "App para gestão de prestação serviços.",
    image: null,
    video: null,
    timeline: { steps: [], currentStep: "" },
  },
];
